### ISSUE TITLE
debug error when I set breakpoint

### ISSUE THREAD

**Issue by yooni126** [BowlerHatLLC/vscode-swf-debug#13]
```
error while processing request 'setBreakpoints'
java.nio.file.InvalidPathException: Illegal char <:> at index 27: AppBazaar_fla.Symbol105_423::frame1
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.as3mxml.vscode.SWFDebugSession.setBreakpoints(SWFDebugSession.java:993)
	at com.as3mxml.vscode.SWFDebugSession.setBreakpoints(SWFDebugSession.java:977)
	at com.as3mxml.vscode.debug.DebugSession.dispatchRequest(DebugSession.java:160)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.dispatch(ProtocolServer.java:143)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.processData(ProtocolServer.java:102)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.start(ProtocolServer.java:81)
	at com.as3mxml.vscode.SWFDebug.main(SWFDebug.java:49)
```
I didn't have this issue, but recenty I see this error for all of my projects !
My vscode version: 1.44.2

{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "swf",
			"request": "launch",
            "name": "Debug (desktop)",
        	"profile": "mobileDevice",
	        "screensize": "iPhoneRetina",
	        "screenDPI": 326,
			"versionPlatform": "WIN",
			"program": "bin/AppBazaar-app.xml",
			"preLaunchTask": "Adobe Animate: compile debug - AppBazaar.fla"
		}
	]
}

**Comment by joshtynjala** [comment]
@yooni126 This issue should be fixed in vscode-swf-debug v1.2.1, which I just released to the Marketplace.
