### ISSUE TITLE
Exceptions occur when debugging mobile devices over wifi

### ISSUE THREAD

**Issue by TomFors** [BowlerHatLLC/vscode-swf-debug#2]
I'm using your extension to debug Adobe AIR on iPhones over wifi, using the attach launch parameter. When debugging I will sometimes hit the default 750ms timeout when using the step functionality. It looks like this can be configured [in the SessionManager class](https://flex.apache.org/maven/flexjs/latest-dev/apidocs/flash/tools/debugger/SessionManager.html#PREF_CONTEXT_RESPONSE_TIMEOUT). Could you expose this in the launch parameters in the future or increase this to be several seconds in length? Also, non-fatal handling of this or other errors would be great.

Here's the exception I get which kills the connection:
`Exception in debugger: flash.tools.debugger.NoResponseException: Timeout occurred while waiting for debugging response from Flash Player for 750 milliseconds
	at flash.tools.debugger.concrete.PlayerSession.stepOverWorker(PlayerSession.java:2960)
	at flash.tools.debugger.concrete.PlayerSession.stepOver(PlayerSession.java:833)
	at flash.tools.debugger.threadsafe.ThreadSafeSession.stepOver(ThreadSafeSession.java:241)
	at com.as3mxml.vscode.SWFDebugSession.next(SWFDebugSession.java:971)
	at com.as3mxml.vscode.debug.DebugSession.dispatchRequest(DebugSession.java:114)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.dispatch(ProtocolServer.java:143)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.processData(ProtocolServer.java:102)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.start(ProtocolServer.java:81)
	at com.as3mxml.vscode.SWFDebug.main(SWFDebug.java:49)
`

Thanks!

**Comment by joshtynjala** [comment]
750 milliseconds seems like an _**extremely**_ long time for the step over command to complete. It makes me think that something has actually gone terribly wrong, and that this is, in fact, a fatal problem.

In other words, I don't think that increasing this timeout would actually make any difference for you...

**Comment by TomFors** [comment]
Wifi debugging is just slow for mobile devices on a large codebase. I'm trying to replace FlashDevelopment and it's able to continue from that exception and I am able to step over code using it. I still see a exception dialog, but it's a non-fatal exception so it keeps going.

**Comment by joshtynjala** [comment]
Understood. I'll see what I can do.

**Comment by joshtynjala** [comment]
Are you certain that the exception is fatal? As best I can tell, the exception is being caught. However, I also manually print the stack trace to the console, so I could see how it might appear to be a crash.

Anyway, I just committed a change where some commands print the error message only (without the stack trace) when NoResponseException is thrown. If I'm right, and the debugger has not disconnected, then that will be a better user experience.

**Comment by joshtynjala** [comment]
@TomFors I just published vscode-swf-debug v1.0.2. Please let me know if this version provides a better experience for you when a command times out. Thanks!

**Comment by TomFors** [comment]
It seems better than previously, but there are still cases where I can get it to drop the connection while debugging. I think having a lot of information shown on the watch or variables window increases the likelihood of it occurring. Mashing the F10 buttons while debugging spits out these logs and then the mobile client hangs:
```
Exception in debugger: flash.tools.debugger.NotSuspendedException: Operation is only allowed when the Flash Player is suspended
	at flash.tools.debugger.concrete.PlayerSession.stepOverWorker(PlayerSession.java:2963)
	at flash.tools.debugger.concrete.PlayerSession.stepOver(PlayerSession.java:833)
	at flash.tools.debugger.threadsafe.ThreadSafeSession.stepOver(ThreadSafeSession.java:241)
	at com.as3mxml.vscode.SWFDebugSession.next(SWFDebugSession.java:988)
	at com.as3mxml.vscode.debug.DebugSession.dispatchRequest(DebugSession.java:114)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.dispatch(ProtocolServer.java:143)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.processData(ProtocolServer.java:102)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.start(ProtocolServer.java:81)
	at com.as3mxml.vscode.SWFDebug.main(SWFDebug.java:49)

Exception in debugger: flash.tools.debugger.NotSuspendedException: Operation is only allowed when the Flash Player is suspended
	at flash.tools.debugger.concrete.PlayerSession.stepOverWorker(PlayerSession.java:2963)
	at flash.tools.debugger.concrete.PlayerSession.stepOver(PlayerSession.java:833)
	at flash.tools.debugger.threadsafe.ThreadSafeSession.stepOver(ThreadSafeSession.java:241)
	at com.as3mxml.vscode.SWFDebugSession.next(SWFDebugSession.java:988)
	at com.as3mxml.vscode.debug.DebugSession.dispatchRequest(DebugSession.java:114)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.dispatch(ProtocolServer.java:143)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.processData(ProtocolServer.java:102)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.start(ProtocolServer.java:81)
	at com.as3mxml.vscode.SWFDebug.main(SWFDebug.java:49)

Timeout occurred while waiting for debugging response from Flash Player for 750 milliseconds
```

The debugger UI acts as if the code is running but the app isn't responding (because it's still in a debug break). Hitting the disconnect button resumes the app but disconnects the debugger connection.

**Comment by joshtynjala** [comment]
Thanks. I should be able to tweak the behavior a bit to avoid the NotSuspendedExceptions.
